# Generated by Django 3.0.4 on 2020-03-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('to-do', 'to-do'), ('in-process', 'in-process'), ('done', 'done')], max_length=50)),
            ],
        ),
    ]
